In [1]:
import pandas as pd
import numpy as np

In [26]:
np.eye(N=3, M=2,dtype=np.int64)*7

array([[7, 0],
       [0, 7],
       [0, 0]], dtype=int64)

In [27]:
np.eye(N=3, M=2, k=-1, dtype=np.int64)*4

array([[0, 0],
       [4, 0],
       [0, 4]], dtype=int64)

In [38]:
(np.eye(N=3, M=2,dtype=np.int64)*7+np.eye(N=3, M=2, k=-1, dtype=np.int64)*4)

array([[7, 0],
       [4, 7],
       [0, 4]], dtype=int64)

In [39]:
dd = np.eye(N=3, M=2, k=-1, dtype=np.int64)*4

In [45]:
dd[1]

array([4, 0], dtype=int64)

In [ ]:
# 부분합이 넘지 않는 것을 구해서
# 원순열로 풀어보자